### ISSUE TITLE
May I suggest here? Add the Scratch Wiki favicon to the skin

### ISSUE THREAD

**Issue by Rumanti** [LLK/scratchwikiskin#34]
It would be very helpful if the code for adding favicon is included in this repository. I don't have enough PHP experience to do this myself. Please consider this.

Also, if suggestions are not acceptable in the Issues section, please tell me where I can suggest things so that I may avoid this mistake in the future. Thanks!

**Comment by maxamillion40** [comment]
You can suggest here or post them on my Scratch account. I don't think adding the favicon code is really a big issue.

**Comment by Rumanti** [comment]
Yeah, I know. But I'm remaking the skin (https://github.com/Rumanti/ScratchIndoWiki-Skin) for Indonesian Scratch Wiki, and it would be nice to add the favicon right now, before I actually send the skin code to the DACH Scratch Wiki team. I don't want to bother them by making them updating frequently.

**Comment by maxamillion40** [comment]
I don't know what the code is then. Sorry.

**Comment by Rumanti** [comment]
After this months, I found out that the favicon should be set up in LocalSettings.php and not in the skin. My mistake.
