### ISSUE TITLE
Update favicon

### ISSUE THREAD

**Issue by Kenny2github** [LLK/scratchwikiskin#42]
[We on the Wiki](https://wiki.scratch.mit.edu/wiki/Scratch_Wiki_talk:Community_Portal#Change_favicon) feel like the favicon needs to be updated to this image:
![Wiki.png](https://wiki.scratch.mit.edu/w/images/Wiki_icon.png)
Since I can't seem to find where the favicon is stored/specified, I'm just making an issue for it instead of a pull request.

Thanks.

**Comment by VutonDesign** [comment]
Support 👍

**Comment by Kenny2github** [comment]
Done after the [transfer](https://en.scratch-wiki.info/wiki/Scratch_Wiki#Server_Transfer)
